version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update && apt-get install curl -y
      - curl -SL "https://nodejs.org/dist/v8.11.1/node-v8.11.1-linux-x64.tar.gz" --output nodejs.tar.gz
      - tar -xzf "nodejs.tar.gz" -C /usr/local --strip-components=1
      - rm nodejs.tar.gz && ln -s /usr/local/bin/node /usr/local/bin/nodejs
      - node -v && npm -v
  build:
    commands:
      - dotnet restore
      - dotnet publish
artifacts:
  files:
    - bin/Debug/netcoreapp2.0/*
